name: CI

on:
  pull_request:
    branches: ["**"]

  push:
    branches: ["main"]

  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3
  DO_NOT_TRACK: true

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Code Checks
        run: bun run check

      - name: Type Checks
        run: bun run typecheck

      - name: Self Check
        run: bun run self-check

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            name: macOS
          - os: ubuntu-latest
            name: Ubuntu

    name: Test (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Test
        run: bun run test
